### ISSUE TITLE
Can't run bundle exec cucumber --tags on any of the tags on the scenarios

### ISSUE THREAD

**Issue by lummyare** [calabash/ios-smoke-test-app#77]
Can't run bundle exec cucumber --tags on any of the tags on the scenarios.
I got the following error:

cucumber.yml was found, but could not be parsed with ERB.  Please refer to cucumber's documentation on correct profile usage.
#<Errno::ENOENT: No such file or directory @ dir_s_mkdir - ./reports/neptune>

Please how can i make this test run on simulators and real devices? what do i need to change in the cucumber.yml to make this run for me please?
Thanks
Lummy

**Comment by tk8817** [comment]
@lummyare this is almost certainly not a calabash issue. The cucumber.yml is driven by the Cucumber project and it sounds like you have some invalid syntax in that file. I would advise that you open a question on the cucumber-ruby gitter and ensure that you post a full log along with the contents of the cucumber.yml

The issues section of a related library is not the ideal place to ask such a question.

**Comment by jmoody** [comment]
@lummyare There is bug in the cucumber.yml.  I don't recall what it is, but I don't have time to fix it right now. 

Something in the devices ERB section.

Pull requests welcome.

**Comment by ark-konopacki** [comment]
@lummyare can you share how your `cucumber.yml` looks like?
i'm able to use tags with `cucumber.yml` looks like that: 
```
default: features --tags ~@non_functional
jenkins_gateway: features --tags @gateway
```
and i can run `@gateway` tests with 
`bundle exec cucumber --tags @gateway`

so for me your questions is "How to configure `cucumber.yml` to run tests on a device/simulator based on used tag" and it is not calabash bug ;)

**Comment by lummyare** [comment]
Thanks for your reply @ark-konopacki ,
I was trying to run the CalSmokeApp from Jmoody's ios-smoke-test-app and here is the cucumber.yml of his app below:

<%

require 'run_loop'

ss_path = "./screenshots/"
FileUtils.rm_rf(ss_path)
FileUtils.mkdir(ss_path)

xamarin_dir = "#{ENV['HOME']}/.xamarin"
devices = {}
device_list = ['neptune', 'venus', 'earp', 'mars', 'saturn', 'pegasi', 'hat', 'erik', 'denis', 'uranus']
device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid}
  devices[device.to_sym] = ht

  FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")
  FileUtils.mkdir("./reports/#{device}/screenshots") unless File.exists?("./reports/#{device}/screenshots")
end

if ENV["USER"] == "jenkins"
  formatter = "pretty"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

default_app = "./Products/app/CalSmoke-cal/CalSmoke-cal.app"
app = ENV["APP"] || ENV["APP_BUNDLE_PATH"] || default_app

%>

verbose: CALABASH_FULL_CONSOLE_OUTPUT=1 DEBUG=1
common: -f <%= formatter %> SCREENSHOT_PATH=<%= ss_path %>

reset_btw:    RESET_BETWEEN_SCENARIOS=1

app:          APP=<%= app %>

simulator:     -p app -p common --tags ~@device_only --tags ~@device NO_STOP=<%= keep_sim_open_after %>
default:       -p simulator

# required only for devices
bundle_id:    BUNDLE_ID=sh.calaba.CalSmoke-cal

device_common:  -p common -p bundle_id --tags ~@simulator --tags ~@simulator_only

neptune_common: DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common
neptune:           -p neptune_common

venus_common:   DEVICE_TARGET=<%= devices[:venus][:udid] %>   DEVICE_ENDPOINT=<%= devices[:venus][:ip] %> -p device_common
venus:          -p venus_common

earp_common:   DEVICE_TARGET=<%= devices[:earp][:udid] %> DEVICE_ENDPOINT=<%= devices[:earp][:ip] %> -p device_common
earp:          -p earp_common

mars_common:   DEVICE_TARGET=<%= devices[:mars][:udid] %> DEVICE_ENDPOINT=<%= devices[:mars][:ip] %> -p device_common
mars:          -p mars_common

saturn_common:   DEVICE_TARGET=<%= devices[:saturn][:udid] %> DEVICE_ENDPOINT=<%= devices[:saturn][:ip] %> -p device_common
saturn:          -p saturn_common

pegasi_common:   DEVICE_TARGET=<%= devices[:pegasi][:udid] %> DEVICE_ENDPOINT=<%= devices[:pegasi][:ip] %> -p device_common
pegasi:          -p pegasi_common

hat:   DEVICE_TARGET=<%= devices[:hat][:udid] %> DEVICE_ENDPOINT=<%= devices[:hat][:ip] %> -p device_common
erik:   DEVICE_TARGET=<%= devices[:erik][:udid] %> DEVICE_ENDPOINT=<%= devices[:erik][:ip] %> -p device_common
denis: DEVICE_TARGET=<%= devices[:denis][:udid] %> DEVICE_ENDPOINT=<%= devices[:denis][:ip] %> -p device_common
uranus: DEVICE_TARGET=<%= devices[:uranus][:udid] %> DEVICE_ENDPOINT=<%= devices[:uranus][:ip] %> -p device_common


But my own framework cucumber.yml looks like this:

# config/cucumber.yml
##YAML Template

ios: -f 'Slowhandcuke::Formatter' PLATFORM=ios -r features/support -r features/ios/ -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages -f html -o ios-report.html -f junit -o features/report/junit -f json -o features/report/ios-report.json -f rerun --out rerun.txt
android: -f 'Slowhandcuke::Formatter' PLATFORM=android -r features/support -r features/android/ -r features/android/support -r features/android/helpers -r features/step_definitions -r features/android/pages -f html -o android-report.html -f junit -o features/report/junit -f json -o features/report/android-report.json
#ios: -f 'Slowhandcuke::Formatter' PLATFORM=ios SDK_VERSION=8.1 OS=ios8 DEVICE_TARGET=simulator cucumber DEVICE=iphone NO_LAUNCH=0 RESET_BETWEENSCENARIOS=1 -r features/support -r features/ios/ -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages -f html -o ios-report.html -f junit -o features/report/junit -f json -o features/report/report.json

**Comment by klloydh** [comment]
I'm having the same/similar issue after following the instructions in the README. Everything works great until:

```
# A test that is run in Travis CI
$ bundle exec cucumber --tags @travis
```

at which point I get:

```
cucumber.yml was found, but could not be parsed with ERB.  Please refer to cucumber's documentation on correct profile usage.
#<Errno::ENOENT: No such file or directory - ./reports/neptune>
```

**Comment by klloydh** [comment]
@jmoody @ark-konopacki 

Here's my `cucumber.yml`:

```
<%

require 'run_loop'

ss_path = "./screenshots/"
FileUtils.rm_rf(ss_path)
FileUtils.mkdir(ss_path)

xamarin_dir = "#{ENV['HOME']}/.xamarin"
devices = {}
device_list = ['neptune', 'venus', 'earp', 'mars', 'saturn', 'pegasi', 'hat', 'erik', 'denis', 'uranus']
device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid}
  devices[device.to_sym] = ht

  FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")
  FileUtils.mkdir("./reports/#{device}/screenshots") unless File.exists?("./reports/#{device}/screenshots")
end

if ENV["USER"] == "jenkins"
  formatter = "pretty"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

default_app = "./Products/app/CalSmoke-cal/CalSmoke-cal.app"
app = ENV["APP"] || ENV["APP_BUNDLE_PATH"] || default_app

%>

verbose: CALABASH_FULL_CONSOLE_OUTPUT=1 DEBUG=1
common: -f <%= formatter %> SCREENSHOT_PATH=<%= ss_path %>

reset_btw:    RESET_BETWEEN_SCENARIOS=1

app:          APP=<%= app %>

simulator:     -p app -p common --tags ~@device_only --tags ~@device NO_STOP=<%= keep_sim_open_after %>
default:       -p simulator

# required only for devices
bundle_id:    BUNDLE_ID=sh.calaba.CalSmoke-cal

device_common:  -p common -p bundle_id --tags ~@simulator --tags ~@simulator_only

neptune_common: DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common
neptune:           -p neptune_common

venus_common:   DEVICE_TARGET=<%= devices[:venus][:udid] %> DEVICE_ENDPOINT=<%= devices[:venus][:ip] %> -p device_common
venus:          -p venus_common

earp_common:   DEVICE_TARGET=<%= devices[:earp][:udid] %> DEVICE_ENDPOINT=<%= devices[:earp][:ip] %> -p device_common
earp:          -p earp_common

mars_common:   DEVICE_TARGET=<%= devices[:mars][:udid] %> DEVICE_ENDPOINT=<%= devices[:mars][:ip] %> -p device_common
mars:          -p mars_common

saturn_common:   DEVICE_TARGET=<%= devices[:saturn][:udid] %> DEVICE_ENDPOINT=<%= devices[:saturn][:ip] %> -p device_common
saturn:          -p saturn_common

pegasi_common:   DEVICE_TARGET=<%= devices[:pegasi][:udid] %> DEVICE_ENDPOINT=<%= devices[:pegasi][:ip] %> -p device_common
pegasi:          -p pegasi_common

hat:   DEVICE_TARGET=<%= devices[:hat][:udid] %> DEVICE_ENDPOINT=<%= devices[:hat][:ip] %> -p device_common
erik:   DEVICE_TARGET=<%= devices[:erik][:udid] %> DEVICE_ENDPOINT=<%= devices[:erik][:ip] %> -p device_common
denis: DEVICE_TARGET=<%= devices[:denis][:udid] %> DEVICE_ENDPOINT=<%= devices[:denis][:ip] %> -p device_common
uranus: DEVICE_TARGET=<%= devices[:uranus][:udid] %> DEVICE_ENDPOINT=<%= devices[:uranus][:ip] %> -p device_common
```

**Comment by ark-konopacki** [comment]
@klloydh i can only suggest to reduce complexity of `cucumber.yml` and start adding features to it one by one (after check if previous working)
But this one 
```
 cucumber.yml was found, but could not be parsed with ERB.  Please refer to cucumber's documentation on correct profile usage.
#<Errno::ENOENT: No such file or directory - ./reports/neptune>
```
definitely not related with calabash 

`FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")`
maybe this is the issue, but i'm only guessing

**Comment by jmoody** [comment]
I will be pushing a fix at some point.  There is a problem in the cucumber.yml.

You can probably just remove the file all together and run.

**Comment by jmoody** [comment]
This is fixed in /master

**Comment by lummyare** [comment]
Still not working for me as i get same error
