### ISSUE TITLE
cannot clone ios smoke test

### ISSUE THREAD

**Issue by AndreiD** [calabash/ios-smoke-test-app#83]
hello.

dans-iMac:Documents dan$ git clone --depth 10 git@github.com:calabash/ios-smoke-test-app.git
Cloning into 'ios-smoke-test-app'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jmoody** [comment]
Are you on Sierra?  If so, it is likely that you are encountering a change in the way ssh keys are loaded. 

This is not a bug in this repo.

Contact GitHub support?  Or try to clone using https URL?
