### ISSUE TITLE
I cant do make ipa-cal

### ISSUE THREAD

**Issue by lummyare** [calabash/ios-smoke-test-app#84]
I am getting this error:
❌  Code Sign error: No matching provisioning profile found: Your build settings specify a provisioning profile with the UUID “XXXXXXXX-8de9-401b-99ff-7dd3c76d3888”, however, no such provisioning profile was found.
 Please what else do i need to change?

**Comment by jmoody** [comment]
You need to update the Xcode project code signing settings.

Starting with Xcode 8 we must hard code the signing settings.

**Comment by lummyare** [comment]
Please how do i update the Xcode project code signing settings and where please?

I am still running this on Xcode 7 could that be a problem?

Please kindly help give more details on how to update the code signing settings or hard code . Thanks
